[versions]
agp = "8.9.1"
kotlin = "2.1.20"
libxposed = "102.0.0"

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
